name: Release Pipeline

on:
  push:
    branches:
      - "release/*"

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org/"

      - name: Install dependencies
        run: yarn install

      - name: Extract version from branch name
        id: version
        run: echo "VERSION=${GITHUB_REF#refs/heads/release/}" >> $GITHUB_ENV

      - name: Update package.json version
        run: npm version ${{ env.VERSION }} --no-git-tag-version

      - name: Run Lint
        run: yarn lint

      - name: Run Build
        run: yarn build

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json
          git commit -m "chore: bump version to ${{ env.VERSION }}"
          git push https://${{ secrets.PAT }}@github.com/ivankoop/ionic-capacitor-biometric.git HEAD:${GITHUB_REF}

      - name: Publish to npm
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create Release Tag
        run: |
          git tag ${{ env.VERSION }}
          git push https://${{ secrets.PAT }}@github.com/ivankoop/ionic-capacitor-biometric.git ${{ env.VERSION }}
          git push https://${{ secrets.PAT }}@github.com/ivankoop/ionic-capacitor-biometric.git --tags

      - name: Get Previous Tag
        id: previoustag
        run: echo "PREVIOUS_TAG=$(git describe --tags --abbrev=0 ${{ env.VERSION }}^)" >> $GITHUB_ENV

      - name: Generate Release Notes
        id: releasenotes
        run: |
          RELEASE_NOTES=$(git log v1.0.6..v1.0.7 --pretty=format:"* %s" --reverse)
          echo "RELEASE_NOTES<<EOF" >> $GITHUB_ENV
          echo "$RELEASE_NOTES" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        with:
          tag_name: ${{ env.VERSION }}
          release_name: Release ${{ env.VERSION }}
          body: ${{ env.RELEASE_NOTES }}
          draft: false
          prerelease: false
